@startuml
+interface NFL_Player{
+<<constructor>>NFL_Player() {...}
playerArray[]
==constructor objects==
playerKey : int
firstName : String
lastName : String
position : String
teamName : String

}


@enduml

